"""add state column

Revision ID: c4a9e23a9a6a
Revises: 352a78d78066
Create Date: 2017-10-03 01:28:22.093992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4a9e23a9a6a'
down_revision = '352a78d78066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE state_type AS ENUM ('registered', 'unregistered')")
    op.add_column('users', sa.Column('state', postgresql.ENUM('registered',
        'unregistered', name='state_type', create_type=True), server_default='unregistered', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.execute('DROP TYPE state_type')
    # ### end Alembic commands ###
