"""Add deadline and grades array.

Revision ID: d58615acb9b8
Revises: 5e02fd8614be
Create Date: 2017-11-01 22:28:56.978026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58615acb9b8'
down_revision = '5e02fd8614be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('deadline', sa.DateTime(), nullable=False))
    op.drop_column('homeworks', 'total_pts')
    op.drop_column('homeworks', 'n_func')
    op.add_column('submissions', sa.Column('expired', sa.Boolean(), nullable=False))
    op.add_column('submissions', sa.Column('grades', sa.ARRAY(sa.Float(precision=32)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'grades')
    op.drop_column('submissions', 'expired')
    op.add_column('homeworks', sa.Column('n_func', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('homeworks', sa.Column('total_pts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('homeworks', 'deadline')
    # ### end Alembic commands ###
